import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Product, HeroBanner, FooterBanner } from '../components/exports'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroBanner />

      <div className='products-heading'>
        <h2>Best selling products</h2>
        <p> Speakers of many variations</p>
      </div>
      <div className='products-container'>
        {['Product 1', 'Product 2'].map((product) => (product))}
      </div>

      <FooterBanner />

    </>
  )
}
