import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Product, HeroBanner, FooterBanner } from '../components/exports'
import { client } from '../lib/sanity'
import { IBanner, IProduct } from 'app-types'
const inter = Inter({ subsets: ['latin'] })

interface IProps {
  allBanners: IBanner[],
  allProducts: IProduct[]
}

export default function Home({ allProducts, allBanners }: IProps) {
  return (
    <>
      <Head>
        <title>EStore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroBanner heroBanner={allBanners[0]} />

      <div className='products-heading'>
        <h2>Best selling products</h2>
        <p> Speakers of many variations</p>
      </div>
      <div className='products-container'>
        {allProducts?.map((product) => (<Product key={product._id} product={product} />))}
      </div>

      <FooterBanner footerBanner={allBanners[0]} />

    </>
  )
}

export const getServerSideProps = async () => {
  const queryGetAllProducts = '*[_type == "product"]'
  const allProducts = await client.fetch(queryGetAllProducts)

  const queryGetAllBanners = '*[_type == "banner"]'
  const allBanners = await client.fetch(queryGetAllBanners)

  return {
    props: {
      allProducts, allBanners
    }
  }
}